version: "3"
services:
  master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    container_name: spark-master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      #SPARK_SUBMIT_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=4000 #debug
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4041:4040
      - 6066:6066
      - 7077:7077
      - 8081:8080
      - 4000:4000 #debug
    volumes:
      - ./volumes/spark-master/conf:/conf
      - ./volumes/spark-master/data:/tmp/data
    networks: 
      - spark
  worker1:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker1
    container_name: spark-worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8082:8081
    volumes:
      - ./volumes/spark-worker1/conf:/conf
      - ./volumes/spark-worker1/data:/tmp/data
    networks: 
      - spark
  worker2:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker2
    container_name: spark-worker2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8083:8081
    volumes:
      - ./volumes/spark-worker2/conf:/conf
      - ./volumes/spark-worker2/data:/tmp/data
    networks: 
      - spark

networks:
  spark:
    ipam:
      driver: default
      config:
       - subnet: 172.19.0.0/24